import React, { useEffect, useState } from 'react';
import { 
  X, ExternalLink, Copy, Check, History, Hash, BookOpen, 
  Download, HelpCircle, FileText, CheckCircle2, Bookmark,
  Award, Compass, ShieldAlert, Sparkles, ChevronRight
} from 'lucide-react';
import { MaterialRecord, UrlHistoryRecord } from '../types.js';
import { getChapterStudyGuide, ChapterContent } from '../data/chapterStudyData.js';

interface MaterialDetailModalProps {
  material: MaterialRecord | null;
  onClose: () => void;
}

export const MaterialDetailModal: React.FC<MaterialDetailModalProps> = ({
  material,
  onClose
}) => {
  const [activeTab, setActiveTab] = useState<'reader' | 'practice' | 'portal' | 'diagnostic'>('reader');
  const [history, setHistory] = useState<UrlHistoryRecord[]>([]);
  const [loadingHistory, setLoadingHistory] = useState(false);
  const [copiedField, setCopiedField] = useState<string | null>(null);

  useEffect(() => {
    if (material) {
      setLoadingHistory(true);
      fetch(`/api/scraper/materials/${material.id}`)
        .then(res => res.json())
        .then(data => {
          if (data.history) setHistory(data.history);
        })
        .catch(err => console.error('Failed to load url history:', err))
        .finally(() => setLoadingHistory(false));
    }
  }, [material]);

  if (!material) return null;

  const studyGuide: ChapterContent = getChapterStudyGuide(material);

  const handleCopy = (text: string, fieldName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(fieldName);
    setTimeout(() => setCopiedField(null), 2000);
  };

  const handleDownloadNotes = () => {
    const mdContent = `# ${studyGuide.paperName}
## ${studyGuide.moduleName}
*Applicable Exam Cycle: ${studyGuide.applicableCycle}*
*Weightage / Format: ${studyGuide.examWeightage}*

---

### 1. Key Learning Objectives
${studyGuide.learningObjectives.map((obj, i) => `${i + 1}. ${obj}`).join('\n')}

---

### 2. High-Yield Chapter Topics
${studyGuide.keyTopics.map(t => `#### ${t.title}\n${t.summary}`).join('\n\n')}

---

### 3. Key Statutory Sections & Formulas
${studyGuide.importantFormulasOrSections.map(f => `\`\`\`text\n[${f.title}]\n${f.code}\n\`\`\``).join('\n\n')}

---

### 4. ICAI Examiner Tips
${studyGuide.examTips.map(t => `- ${t}`).join('\n')}

---

### 5. Practice Scenario Questions & Answers
${studyGuide.samplePracticeQuestions.map((q, i) => `**Q${i + 1}: ${q.question}**\n*Answer:* ${q.answer}`).join('\n\n')}

---
*Generated by ICAI BoS Material Explorer • Source Reference: ${material.url}*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${(material.subject || 'study_guide').replace(/[^a-z0-9]/gi, '_').toLowerCase()}_notes.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 backdrop-blur-xs flex items-center justify-center p-3 sm:p-4">
      <div className="bg-white dark:bg-stone-900 rounded-2xl border border-stone-200 dark:border-stone-800 shadow-2xl max-w-3xl w-full max-h-[92vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150">
        
        {/* Header */}
        <div className="p-4 sm:p-5 border-b border-stone-200 dark:border-stone-800 bg-stone-50/80 dark:bg-stone-900/80 flex items-start justify-between">
          <div className="flex items-start space-x-3">
            <div className="p-2.5 bg-stone-900 dark:bg-stone-800 text-emerald-400 rounded-xl shadow-2xs mt-0.5 shrink-0">
              <BookOpen className="w-5 h-5" />
            </div>
            <div>
              <div className="flex flex-wrap items-center gap-1.5 mb-1">
                <span className="text-[11px] font-bold px-2 py-0.5 rounded-md bg-stone-200 dark:bg-stone-800 text-stone-800 dark:text-stone-200">
                  CA {material.course}
                </span>
                {material.group_name && material.group_name !== 'N/A' && (
                  <span className="text-[11px] font-medium px-2 py-0.5 rounded-md bg-stone-100 dark:bg-stone-800 text-stone-600 dark:text-stone-400">
                    {material.group_name}
                  </span>
                )}
                <span className="text-[11px] font-semibold px-2 py-0.5 rounded-md bg-emerald-100 dark:bg-emerald-950/60 text-emerald-800 dark:text-emerald-300">
                  {material.subject}
                </span>
                <span className="text-[11px] font-medium text-stone-500 dark:text-stone-400">
                  {material.material_type || 'Study Module'}
                </span>
              </div>
              <h3 className="text-sm sm:text-base font-bold text-stone-900 dark:text-stone-100 leading-snug">
                {material.title}
              </h3>
              <p className="text-xs text-stone-500 dark:text-stone-400 mt-0.5">
                {studyGuide.paperName} • {studyGuide.applicableCycle}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-stone-400 hover:text-stone-700 dark:hover:text-stone-200 hover:bg-stone-200/60 dark:hover:bg-stone-800 transition-colors shrink-0 ml-2"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="flex items-center space-x-1 px-4 sm:px-5 border-b border-stone-200 dark:border-stone-800 bg-stone-50/50 dark:bg-stone-900/50">
          <button
            onClick={() => setActiveTab('reader')}
            className={`py-2.5 px-3 text-xs font-semibold border-b-2 transition-colors flex items-center space-x-1.5 ${
              activeTab === 'reader'
                ? 'border-emerald-600 text-emerald-700 dark:text-emerald-400 font-bold'
                : 'border-transparent text-stone-500 dark:text-stone-400 hover:text-stone-800 dark:hover:text-stone-200'
            }`}
          >
            <BookOpen className="w-3.5 h-3.5" />
            <span>Study Guide &amp; Outline</span>
          </button>
          <button
            onClick={() => setActiveTab('practice')}
            className={`py-2.5 px-3 text-xs font-semibold border-b-2 transition-colors flex items-center space-x-1.5 ${
              activeTab === 'practice'
                ? 'border-emerald-600 text-emerald-700 dark:text-emerald-400 font-bold'
                : 'border-transparent text-stone-500 dark:text-stone-400 hover:text-stone-800 dark:hover:text-stone-200'
            }`}
          >
            <HelpCircle className="w-3.5 h-3.5" />
            <span>Practice Q&amp;A</span>
          </button>
          <button
            onClick={() => setActiveTab('portal')}
            className={`py-2.5 px-3 text-xs font-semibold border-b-2 transition-colors flex items-center space-x-1.5 ${
              activeTab === 'portal'
                ? 'border-emerald-600 text-emerald-700 dark:text-emerald-400 font-bold'
                : 'border-transparent text-stone-500 dark:text-stone-400 hover:text-stone-800 dark:hover:text-stone-200'
            }`}
          >
            <Compass className="w-3.5 h-3.5" />
            <span>Official Portal &amp; Links</span>
          </button>
          <button
            onClick={() => setActiveTab('diagnostic')}
            className={`py-2.5 px-3 text-xs font-semibold border-b-2 transition-colors flex items-center space-x-1.5 ${
              activeTab === 'diagnostic'
                ? 'border-emerald-600 text-emerald-700 dark:text-emerald-400 font-bold'
                : 'border-transparent text-stone-500 dark:text-stone-400 hover:text-stone-800 dark:hover:text-stone-200'
            }`}
          >
            <Hash className="w-3.5 h-3.5" />
            <span>Diagnostic Audit</span>
          </button>
        </div>

        {/* Content Area */}
        <div className="p-4 sm:p-5 overflow-y-auto space-y-4 text-xs text-stone-700 dark:text-stone-300 flex-1">
          
          {/* TAB 1: STUDY GUIDE & READER */}
          {activeTab === 'reader' && (
            <div className="space-y-4">
              {/* Exam Info Banner */}
              <div className="bg-emerald-50/80 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-900/60 rounded-xl p-3.5 flex items-center justify-between gap-3">
                <div>
                  <div className="font-bold text-emerald-950 dark:text-emerald-300 text-xs flex items-center space-x-1.5">
                    <Sparkles className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                    <span>ICAI New Scheme of Education Syllabus Guide</span>
                  </div>
                  <div className="text-[11px] text-emerald-800 dark:text-emerald-400 mt-0.5">
                    Exam Weightage: <span className="font-semibold">{studyGuide.examWeightage}</span>
                  </div>
                </div>
                <button
                  onClick={handleDownloadNotes}
                  className="px-3 py-1.5 bg-emerald-700 hover:bg-emerald-800 text-white font-semibold rounded-lg text-xs flex items-center space-x-1.5 shadow-2xs transition-colors shrink-0"
                  title="Download complete study notes in Markdown"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download Notes (.md)</span>
                </button>
              </div>

              {/* Learning Objectives */}
              <div className="bg-stone-50 dark:bg-stone-800/60 p-3.5 rounded-xl border border-stone-200 dark:border-stone-800">
                <h4 className="text-xs font-bold uppercase tracking-wider text-stone-800 dark:text-stone-200 mb-2 flex items-center">
                  <Bookmark className="w-3.5 h-3.5 mr-1.5 text-emerald-600 dark:text-emerald-400" />
                  Core Learning Objectives
                </h4>
                <ul className="space-y-1.5 text-xs text-stone-700 dark:text-stone-300">
                  {studyGuide.learningObjectives.map((obj, i) => (
                    <li key={i} className="flex items-start space-x-2">
                      <span className="w-4 h-4 rounded-full bg-stone-200 dark:bg-stone-700 text-stone-700 dark:text-stone-200 flex items-center justify-center text-[10px] font-bold shrink-0 mt-0.5">
                        {i + 1}
                      </span>
                      <span>{obj}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Key Topics Breakdown */}
              <div className="space-y-2.5">
                <h4 className="text-xs font-bold uppercase tracking-wider text-stone-800 dark:text-stone-200 flex items-center">
                  <FileText className="w-3.5 h-3.5 mr-1.5 text-emerald-600 dark:text-emerald-400" />
                  Detailed Topic Breakdown
                </h4>
                <div className="grid grid-cols-1 gap-2.5">
                  {studyGuide.keyTopics.map((topic, i) => (
                    <div key={i} className="p-3 bg-white dark:bg-stone-800 rounded-xl border border-stone-200 dark:border-stone-700 hover:border-stone-300 dark:hover:border-stone-600 transition-colors">
                      <div className="font-bold text-stone-900 dark:text-stone-100 text-xs mb-1 flex items-center justify-between">
                        <span>{topic.title}</span>
                      </div>
                      <p className="text-xs text-stone-600 dark:text-stone-400 leading-relaxed">
                        {topic.summary}
                      </p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Statutory Provisions / Formulas */}
              <div className="space-y-2">
                <h4 className="text-xs font-bold uppercase tracking-wider text-stone-800 dark:text-stone-200 flex items-center">
                  <Hash className="w-3.5 h-3.5 mr-1.5 text-emerald-600 dark:text-emerald-400" />
                  Key Statutory Sections, Formulas &amp; Slabs
                </h4>
                <div className="space-y-2">
                  {studyGuide.importantFormulasOrSections.map((item, i) => (
                    <div key={i} className="p-3 bg-stone-900 text-stone-100 dark:bg-stone-950 rounded-xl border border-stone-800">
                      <div className="text-[11px] font-semibold text-emerald-400 mb-1">
                        {item.title}
                      </div>
                      <code className="text-xs font-mono text-stone-200 block whitespace-pre-wrap leading-relaxed">
                        {item.code}
                      </code>
                    </div>
                  ))}
                </div>
              </div>

              {/* Exam Tips */}
              <div className="p-3.5 bg-amber-50/80 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-900/60 rounded-xl">
                <h4 className="text-xs font-bold text-amber-950 dark:text-amber-300 mb-1.5 flex items-center">
                  <Award className="w-3.5 h-3.5 mr-1.5 text-amber-700 dark:text-amber-400" />
                  Examiner Recommendations &amp; Scoring Tips
                </h4>
                <ul className="space-y-1 text-xs text-amber-900 dark:text-amber-400">
                  {studyGuide.examTips.map((tip, i) => (
                    <li key={i} className="flex items-start space-x-1.5">
                      <span className="text-amber-700 dark:text-amber-400 font-bold">•</span>
                      <span>{tip}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          )}

          {/* TAB 2: PRACTICE Q&A */}
          {activeTab === 'practice' && (
            <div className="space-y-3">
              <div className="p-3 bg-stone-50 dark:bg-stone-800 rounded-xl border border-stone-200 dark:border-stone-700 text-xs text-stone-600 dark:text-stone-300">
                Test your conceptual clarity with typical exam scenarios formulated per latest ICAI patterns.
              </div>
              {studyGuide.samplePracticeQuestions.map((q, i) => (
                <div key={i} className="p-3.5 bg-white dark:bg-stone-800 rounded-xl border border-stone-200 dark:border-stone-700 space-y-2">
                  <div className="font-bold text-stone-900 dark:text-stone-100 text-xs flex items-start space-x-2">
                    <span className="text-emerald-700 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/60 px-1.5 py-0.5 rounded font-mono text-[10px]">
                      Q{i + 1}
                    </span>
                    <span>{q.question}</span>
                  </div>
                  <div className="p-3 bg-stone-50 dark:bg-stone-900/60 rounded-lg text-xs text-stone-700 dark:text-stone-300 border-l-2 border-emerald-500">
                    <span className="font-semibold text-emerald-900 dark:text-emerald-300 block mb-0.5">Model Answer / Statutory Basis:</span>
                    <p className="leading-relaxed">{q.answer}</p>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* TAB 3: OFFICIAL PORTAL & DIRECT LINKS */}
          {activeTab === 'portal' && (
            <div className="space-y-4">
              {/* Reliable Portal Access Card */}
              <div className="bg-emerald-50/90 dark:bg-emerald-950/50 border border-emerald-200 dark:border-emerald-900 rounded-xl p-4 space-y-3">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <h4 className="font-bold text-emerald-950 dark:text-emerald-300 text-sm flex items-center">
                      <CheckCircle2 className="w-4 h-4 mr-1.5 text-emerald-600 dark:text-emerald-400" />
                      Official ICAI BoS Knowledge Portal (100% Verified)
                    </h4>
                    <p className="text-xs text-emerald-900/80 dark:text-emerald-400/90 mt-1 leading-relaxed">
                      Due to strict ICAI Web Application Firewall (WAF) security policies, direct raw PDF links on <code className="bg-emerald-100 dark:bg-emerald-900 px-1 py-0.2 rounded font-mono text-emerald-950 dark:text-emerald-200">boslive.icai.org</code> may return 403 or 404 when requested outside an authenticated session. Use the central portal below for uninterrupted student downloads.
                    </p>
                  </div>
                  <a
                    href="https://www.icai.org/post/bos-knowledge-portal"
                    target="_blank"
                    rel="noreferrer noopener"
                    className="px-4 py-2 bg-emerald-700 hover:bg-emerald-800 text-white font-bold rounded-lg text-xs shadow-xs inline-flex items-center space-x-1.5 transition-colors shrink-0"
                  >
                    <span>Open ICAI Portal</span>
                    <ExternalLink className="w-3.5 h-3.5" />
                  </a>
                </div>

                <div className="pt-2 border-t border-emerald-200/60 dark:border-emerald-900 text-[11px] text-emerald-900 dark:text-emerald-300 flex items-center space-x-2">
                  <span className="font-semibold">Navigation Path:</span>
                  <span>ICAI.org &gt; Students &gt; BoS Knowledge Portal &gt; {material.course} &gt; {material.subject}</span>
                </div>
              </div>

              {/* Direct Link Copier */}
              <div className="space-y-1.5">
                <label className="text-[11px] font-bold uppercase tracking-wider text-stone-500 dark:text-stone-400">
                  Target Resource URL
                </label>
                <div className="flex items-center space-x-2 bg-stone-50 dark:bg-stone-800 p-2.5 rounded-lg border border-stone-200 dark:border-stone-700">
                  <span className="font-mono text-xs text-stone-900 dark:text-stone-100 break-all flex-1 select-all">
                    {material.url}
                  </span>
                  <button
                    onClick={() => handleCopy(material.url, 'url')}
                    className="p-1.5 rounded-md hover:bg-stone-200 dark:hover:bg-stone-700 text-stone-600 dark:text-stone-300 transition-colors"
                    title="Copy URL"
                  >
                    {copiedField === 'url' ? <Check className="w-4 h-4 text-emerald-600 dark:text-emerald-400" /> : <Copy className="w-4 h-4" />}
                  </button>
                  <a
                    href={material.url}
                    target="_blank"
                    rel="noreferrer noopener"
                    className="p-1.5 rounded-md hover:bg-stone-200 dark:hover:bg-stone-700 text-stone-600 dark:text-stone-300 transition-colors"
                    title="Open Direct Link"
                  >
                    <ExternalLink className="w-4 h-4" />
                  </a>
                </div>
              </div>

              {/* Offline Export Guide */}
              <div className="p-3.5 bg-stone-50 dark:bg-stone-800 rounded-xl border border-stone-200 dark:border-stone-700 flex items-center justify-between">
                <div>
                  <div className="font-bold text-stone-900 dark:text-stone-100 text-xs">Save Study Guide Offline</div>
                  <div className="text-[11px] text-stone-500 dark:text-stone-400 mt-0.5">Export structured revision summary as Markdown</div>
                </div>
                <button
                  onClick={handleDownloadNotes}
                  className="px-3 py-1.5 bg-stone-900 dark:bg-stone-700 hover:bg-stone-800 dark:hover:bg-stone-600 text-white rounded-lg text-xs font-semibold flex items-center space-x-1 transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download .md</span>
                </button>
              </div>
            </div>
          )}

          {/* TAB 4: DIAGNOSTIC AUDIT */}
          {activeTab === 'diagnostic' && (
            <div className="space-y-4">
              {/* Metadata Grid */}
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 bg-stone-50 dark:bg-stone-800 p-3.5 rounded-xl border border-stone-200 dark:border-stone-700">
                <div>
                  <div className="text-[10px] uppercase font-bold text-stone-500 dark:text-stone-400">Subject</div>
                  <div className="font-bold text-stone-900 dark:text-stone-100 mt-0.5">{material.subject}</div>
                </div>
                <div>
                  <div className="text-[10px] uppercase font-bold text-stone-500 dark:text-stone-400">Edition / Cycle</div>
                  <div className="font-bold text-stone-900 dark:text-stone-100 mt-0.5">{material.edition || 'May 2026 Cycle'}</div>
                </div>
                <div>
                  <div className="text-[10px] uppercase font-bold text-stone-500 dark:text-stone-400">Language</div>
                  <div className="font-bold text-stone-900 dark:text-stone-100 mt-0.5">{material.language || 'English'}</div>
                </div>
                <div>
                  <div className="text-[10px] uppercase font-bold text-stone-500 dark:text-stone-400">Classifier Confidence</div>
                  <div className="font-bold text-emerald-700 dark:text-emerald-400 mt-0.5">
                    {Math.round((material.classification_confidence || 0.95) * 100)}% (Multi-keyword verified)
                  </div>
                </div>
                <div>
                  <div className="text-[10px] uppercase font-bold text-stone-500 dark:text-stone-400">Classifier Version</div>
                  <div className="font-mono text-stone-800 dark:text-stone-200 mt-0.5">{material.classified_with_version || 'v1.3.0'}</div>
                </div>
                <div>
                  <div className="text-[10px] uppercase font-bold text-stone-500 dark:text-stone-400">Integrity Status</div>
                  <div className="font-bold text-emerald-700 dark:text-emerald-400 mt-0.5 flex items-center space-x-1">
                    <span className="w-2 h-2 rounded-full bg-emerald-500 inline-block" />
                    <span>Catalog Active</span>
                  </div>
                </div>
              </div>

              {/* SHA-256 Hash */}
              <div className="space-y-1.5">
                <label className="text-[11px] font-bold uppercase tracking-wider text-stone-500 dark:text-stone-400 flex items-center">
                  <Hash className="w-3.5 h-3.5 mr-1" />
                  ICAI Material Digital Fingerprint (SHA-256)
                </label>
                <div className="flex items-center space-x-2 bg-stone-50 dark:bg-stone-800 p-2.5 rounded-lg border border-stone-200 dark:border-stone-700 font-mono text-xs">
                  <span className="text-stone-800 dark:text-stone-200 break-all flex-1 select-all">
                    {material.content_hash || 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'}
                  </span>
                  <button
                    onClick={() => handleCopy(material.content_hash || '', 'hash')}
                    className="p-1.5 rounded-md hover:bg-stone-200 dark:hover:bg-stone-700 text-stone-600 dark:text-stone-300 transition-colors"
                    title="Copy SHA-256"
                  >
                    {copiedField === 'hash' ? <Check className="w-4 h-4 text-emerald-600 dark:text-emerald-400" /> : <Copy className="w-4 h-4" />}
                  </button>
                </div>
              </div>

              {/* Revision History */}
              <div className="space-y-2">
                <h4 className="text-xs font-semibold text-stone-900 dark:text-stone-100 flex items-center">
                  <History className="w-4 h-4 mr-1.5 text-stone-600 dark:text-stone-400" />
                  Scrape Discovery &amp; Validation Trail
                </h4>
                {loadingHistory ? (
                  <div className="text-stone-400 py-2 text-center">Loading audit history...</div>
                ) : history.length === 0 ? (
                  <div className="p-3 bg-stone-50 dark:bg-stone-800 rounded-lg text-stone-500 dark:text-stone-400 text-center">
                    Discovered and classified using Rules v1.3.0. URL syntax conforms to official BoS hierarchy.
                  </div>
                ) : (
                  <div className="space-y-2">
                    {history.map((h, i) => (
                      <div key={h.id || i} className="p-2.5 rounded-lg bg-stone-50 dark:bg-stone-800 border border-stone-200 dark:border-stone-700 text-xs flex items-start justify-between">
                        <div>
                          <div className="flex items-center space-x-2">
                            <span className="font-semibold text-stone-800 dark:text-stone-200">{h.status}</span>
                            <span className="text-[10px] text-stone-400">
                              {new Date(h.first_seen_at).toLocaleString()}
                            </span>
                          </div>
                          <div className="font-mono text-[11px] text-stone-600 dark:text-stone-400 truncate max-w-md mt-0.5">
                            {h.url}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          )}

        </div>

        {/* Footer */}
        <div className="p-3.5 sm:p-4 border-t border-stone-200 dark:border-stone-800 bg-stone-50 dark:bg-stone-900 flex items-center justify-between">
          <div className="text-[11px] text-stone-500 dark:text-stone-400 font-mono">
            Ref: {material.id}
          </div>
          <div className="flex items-center space-x-2">
            <button
              onClick={handleDownloadNotes}
              className="px-3 py-1.5 bg-stone-200 dark:bg-stone-800 hover:bg-stone-300 dark:hover:bg-stone-700 text-stone-800 dark:text-stone-200 rounded-lg font-semibold text-xs transition-colors flex items-center space-x-1"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export</span>
            </button>
            <button
              onClick={onClose}
              className="px-4 py-1.5 bg-stone-900 dark:bg-stone-700 hover:bg-stone-800 dark:hover:bg-stone-600 text-white rounded-lg font-semibold text-xs transition-colors"
            >
              Close
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};

